- name: Install utils
  ansible.builtin.dnf:
    name: 
      - "epel-release"
    state: present

- name: "Install nagios goodies"
  ansible.builtin.dnf:
    name: 
      - nagios-plugins-all
      - htop
    state: present
    enablerepo:
      - epel-testing
      - powertools
