# - name: "Install repos and basic utils"
#   hosts: all
#   become: true
#   collections:
#     - icinga.icinga
#     - ansible.posix
#   roles:
#     - repos
#     - mafalb.epel.release
#     - mafalb.epel.next
#     - common-settings


# - name: "Install remi repo and databases"
#   hosts: master
#   become: true
#   collections:
#     - icinga.icinga
#     - community.mysql
#     - ansible.posix
#   roles:
#     - remi
#     - icingadb

- name: "Install icinga2"
  hosts: all
  order: sorted
  # serial:
  #   - 1
  become: true
  collections:
    - icinga.icinga
    - ansible.posix
    - community.general
    - community.mysql

  roles:
    - repos
    - mafalb.epel.release
    - mafalb.epel.next
    - common-settings

  pre_tasks:

    - name: Setting host facts using complex arguments
      when: "'masters' not in group_names"
      set_fact:
        icinga2_features: "{{ satellite_icinga2_features }}"

    - name: Setting host facts using complex arguments
      when: "'masters' in group_names"
      set_fact:
        icinga2_features: "{{ master_icinga2_features }}"
  
  tasks:

    - name: "remi repos only on masters"
      include_role:
        name: remi
      when: "'masters' in group_names"

    - name: "icingadb only on masters"
      include_role:
        name: icingadb
      when: "'masters' in group_names"

    - name: "icinga first on masters"
      include_role:
        name: icinga2
      when: "'masters' in group_names"

    - name: "Icinga then on anything other (we need the CA to be in place before continuing)"
      include_role:
        name: icinga2
      when: not 'masters' in group_names

    - name: "icingaweb only on masters"
      include_role:
        name: icingaweb
      when: "'masters' in group_names"

