- hosts: all
  become: true
  collections:
    - icinga.icinga
    - community.mysql
    - ansible.posix
  roles:
    - repos
    - remi
    - mafalb.epel.release
    - mafalb.epel.next
    - icingadb
    - icinga2
    - icingaweb
  pre_tasks:
    # Sadly php-fpm httpd and icinga2 are pretty tedious with selinux.
    - name: "Put SELinux in permissive mode, logging actions that would be blocked."
      ansible.posix.selinux:
        policy: targeted
        state: permissive
  tasks:
    # Install the nagios Plugins
    - name: "Install nagios goodies"
      ansible.builtin.dnf:
        name: 
          - nagios-plugins-all
        state: present
        enablerepo:
          - epel-testing
          - powertools